WalletAdmin/Controllers/CadastroController.cs
using Microsoft.AspNetCore.Mvc;
using NHibernate;
using System.Linq;
using System.Threading.Tasks;
using WalletAdmin.Entidades;
using WalletAdmin.Repositorio;

namespace WalletAdmin.Controllers
{
    public class CadastroController : Controller
    {
        private readonly UsuariosRepositorio usuariosRepositorio;
        public CadastroController(NHibernate.ISession session) => usuariosRepositorio = new UsuariosRepositorio(session);
        public ActionResult Cadastro()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Cadastro(Tabela_Usuarios tabela_Usuarios)
        {
            if (ModelState.IsValid)
            {
                await usuariosRepositorio.Add(tabela_Usuarios);
                return RedirectToAction("Index", "Login");
            }
            return View(tabela_Usuarios);
        }
    }
}

WalletAdmin/Views/Cadastro/Cadastro.cshtml
@model WalletAdmin.Entidades.Tabela_Usuarios

<link rel="stylesheet" href="./Sources/Login/fonts/icomoon/style.css">

<link rel="stylesheet" href="./Sources/Login/js/owl.carousel.min.js">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="/Sources/Login/css/bootstrap.min.css">


<div class="row d-flex justify-content-center align-items-center h-100" style="margin-top:100px;">
    <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
                <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                        <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Cadastre-se</p>

                        <form class="mx-1 mx-md-4" asp-controller="Cadastro" asp-action="Cadastro" method="Post">
                            <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                    <input asp-for="Usuario" type="text" id="form3Example1c" class="form-control" placeholder="Usuario" />
                                </div>
                            </div>

                            <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                    <input asp-for="Email" type="email" id="form3Example3c" class="form-control" placeholder="Email" />
                                </div>
                            </div>

                            <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                    <input asp-for="Senha" type="password" id="form3Example4c" class="form-control" placeholder="Senha" />
                                </div>
                            </div>
                            <div class="form-check d-flex justify-content-center mb-5">
                                <input class="form-check-input me-2 " style="margin-right:290px; margin-top:6px;" type="checkbox" value="" id="form2Example3c" />
                                <label class="form-check-label" for="form2Example3">
                                    Concordo com todas as afirmações em <a href="#!">Termos de Serviços</a>
                                </label>
                            </div>
                            <div class="d-flex justify-content-around" >
                                <div class="d-flex justify-content-center ">
                                    <button type="submit" class="btn btn-primary btn-lg">Enviar</button>
                                </div>
                                <div class="d-flex justify-content-center ">
                                    <button type="submit" class="btn btn-primary btn-lg">Voltar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
                        <img src="/assets/images/23672917_6788221.jpg"
                             class="img-fluid" alt="Sample image">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="./Sources/Login/js/jquery-3.3.1.min.js"></script>
<script src="/Sources/Login/js/popper.min.js"></script>
<script src="./Sources/Login/js/bootstrap.min.js"></script>
<script src="./Sources/Login/js/main.js"></script>